# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

# testing
gem "rspec"
gem "factory_girl"

# task running
gem "rake"

# serve to web
gem 'rack'

# build html
gem 'arbre'

gem 'sysinfo'
gem 'hooks'

gem 'cane'
gem 'rubocop'
