#!/usr/bin/env bash

### WIP
### TODO: make this actually work with the augmentations

DIR=`dirname "$0"`

# tsc "$DIR/src/nodeplus/nodeplus.ts" --ou
# node

npx ts-node "$DIR/src/nodeplus/nodeplus.ts"
