<<<<<<< HEAD
#!/usr/bin/ruby
=======
#!/usr/local/bin/ruby
>>>>>>> 11577ce428cdac2cf57847116b2ee6b431bbd597

# GET THE JSON MODULE
require 'json'

# PARSE A JSON OBJECT (IN STRING FORM)
my_hash = JSON.parse('{"hello": "goodbye"}')
puts my_hash # => {"hello"=>"goodbye"}

# RETRIEVE AN ELEMENT FROM THE HASH GENERATED BY PARSING A PARSED JSON OBJECT
puts my_hash["hello"] # => goodbye