#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** EXTRA SUBLIME INFO, HOTKEYS'
echo '---------------------------------------------------------------------------------'
echo "-  see cmd name for each action in console:       sublime.log_commands(True)"
echo ''
echo 'HOTKEYS'
echo "-  Go to definition using mouse click only:       ALT--LEFT_CLICK"
echo "-  clear console if using ClearConsole plugin:    CTRL-ALT-k"
echo "-  rename currently selected file:                ALT-r"
echo "-  create new file in current dir:                ALT-n"
echo "-  create new folder in current dir:              ALT-f"
echo "-  duplicate currently selected file:             ALT-d"
echo "-  open autocompletions menu:                     CTRL-SPACE"
echo "-  toggle side menu:                              CMD-K, B"
echo "-  go to symbol (fns, css blocks, classes, etc.)  CMD-r"
echo "-  select cur scope. Expand more w each tap:      CMD-SHIFT-SPACE"
echo "-  select full contents of current parens:        CTRL-SHIFT-M"
echo "-  insert line before current line:               CMD-SHIFT-ENTER"
echo "-  insert line after current line:                CMD-ENTER"
echo "-  uppercase:                                     CTRL-k, u"
echo "-  lowercase:                                     CTRL-k, l  (ell)"
echo "-  del word forward:                              CTRL-DEL"
echo "-  del word backward:                             CTRL-BACKSPACE"
echo "# HOTKEYS: BOOKMARKS"
echo "-  bookmark location:                             CMD-F2"
echo "-  goto next bookmark::                           F2"
echo "-  goto previous bookmark::                       SHIFT-F2"
echo ""
echo "# HOTKEYS: OPEN FILES"
echo "- open hotkeys file:                              CTRL-CMD-b"
echo ""
echo "# MACROS"
echo "-  Start & stop recording macro:                  CTRL-Q"
echo "-  Playback macro:                                CTRL-SHIFT-Q"
echo ""
echo "# STRINGS"
echo "-  To uppercase:                                  CMD-k,CMD-u    << in sequence"
echo "-  To lowercase:                                  CMD-k,CMD-l    << in sequence"
echo '---------------------------------------------------------------------------------\n'
