#!/usr/bin/env sh

echo ''
echo '--------------------------------------------------------------------------------------------------------'
echo '** GIT **'
echo '--------------------------------------------------------------------------------------------------------'
echo 'DIFF AGAINST A LOCATION IN THE STASH:                git stash show -p stash@{0}'
echo ''
echo 'Clone without .git folder: example:'
echo '        git clone --depth=1 --branch=master https://github.com/ngmy/vim-rubocop.git'
echo "        echo \$(echo !\$ | awk -F'.' '{print \$(NF-1)}' | awk -F'/' '{print \$NF}')/.git | xargs rm -rf"
echo ''
echo 'Comparing state of a file in a past commit with current state (example):'
echo '        git diff e51a122d44aacab0745230076202ae037b17414f..HEAD -- spec/services/report_service_spec.rb'
echo '--------------------------------------------------------------------------------------------------------\n'
