#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** MAC KEYS **'
echo '---------------------------------------------------------------------------------'
echo '- HOTKEYS'
echo "    OPTION-CMD-ESCAPE     Open force quit app selector" 
echo "    SHIFT--CMD-3          Take screenshot"
echo ""
echo "- BROWSER (Chrome)"
echo "    CMD-ALT-I             Open or close Chrome dev tools"
echo ''
echo '- MAC KEY SYMBOLS'
echo '    ⌘     CMD'
echo '    ⌥     OPTION / ALT'
echo '    ^     CTRL / CONTROL'
echo '    ⇧     SHIFT'
echo '    ⇪     CAPS LOCK'
echo '    Fn    FUNCTION'
echo '---------------------------------------------------------------------------------\n'
