#!/usr/bin/env sh

cat <<-'TERMINAL_MANUAL_QUICK_REF'

---------------------------------------------------------------------------------
** NEW_TYPE **
---------------------------------------------------------------------------------
- subtitle

## First item (title here):   general syntax of 'item'
   -- (definition of first item goes here)
   -- example:                example goes here

## List item title:
   -- subitem here:           syntax here
   -- subitem here:           syntax here
   -- subitem here:           syntax here
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
