#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** EMBER CLI **'
echo '---------------------------------------------------------------------------------'
echo "## generate a route:       ember g route route_name"
echo "   -   create route handler, template route renders, and test file for route"
echo '---------------------------------------------------------------------------------\n'
