#!/usr/bin/env sh

cat <<-'TERMINAL_MANUAL_QUICK_REF'

---------------------------------------------------------------------------------
** MAC KEYS **
---------------------------------------------------------------------------------
- HOTKEYS
    OPTION-CMD-ESCAPE     Open force quit app selector
    SHIFT--CMD-3          Take screenshot

- BROWSER (Chrome)
    CMD-ALT-I             Open or close Chrome dev tools

- MAC KEY SYMBOLS
    ⌘     CMD
    ⌥     OPTION / ALT
    ^     CTRL / CONTROL
    ⇧     SHIFT
    ⇪     CAPS LOCK
    Fn    FUNCTION
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
