#!/usr/bin/env sh

cat << END_OF_TERMINAL_MANUAL_FOR_BASIC_REFERENCE

---------------------------------------------------------------------------------
** NEW_TYPE **
---------------------------------------------------------------------------------
- subtitle

## First item (title here):   general syntax of 'item'
   -- (definition of first item goes here)
   -- example:                example goes here

## List item title:
   -- subitem here:           syntax here
   -- subitem here:           syntax here
   -- subitem here:           syntax here

---------------------------------------------------------------------------------\n
END_OF_TERMINAL_MANUAL_FOR_BASIC_REFERENCE