#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** AWK - COMMON USE **'
echo '---------------------------------------------------------------------------------'
echo "- print 2nd-last column:                    awk '{print \$(NF-1)"
echo "- split into columns based on a delimiter:  awk -F'/' '{print \$(NF)}'"
echo "                                              * above, / is the delimiter"
echo ''
echo "## First item (title here):   general syntax of 'item'"
echo "   -- (definition of first item goes here)"
echo "   -- example:                example goes here"
echo ""
echo "## List item title:"
echo "   -- subitem here:           syntax here"
echo "   -- subitem here:           syntax here"
echo "   -- subitem here:           syntax here"
echo ""
echo '---------------------------------------------------------------------------------\n'
