#!/usr/bin/env sh

cat << TERMINAL_MANAUAL_JS_THIS_KEYWORD

---------------------------------------------------------------------------------
** THAT FUCKING JAVASCRIPT "this" KEYWORD (ThisK) **
---------------------------------------------------------------------------------
- "this" (ThisK) in the global scope
  -   "this" (ThisK) is window or undefined

## Standalone function: this is same as global value e.g.
      function ok() { console.log(this); };
      ok(); // => undefined

## Function on an object, called with the name of the object explicitly:
      var myFunc = {
          boo: 'boogaboo',
          ok: function() { console.log(this.boo); }
      };
      myFunc.ok(); // => boogaboo

---------------------------------------------------------------------------------

TERMINAL_MANAUAL_JS_THIS_KEYWORD
