#!/usr/bin/env sh

cat <<-'TERMINAL_EMBER_JS_MANUAL_FOR_REFERENCE'

---------------------------------------------------------------------------------
** EMBER CLI **
---------------------------------------------------------------------------------
## generate a route:       ember g route route_name
   -   create route handler, template route renders, and test file for route
---------------------------------------------------------------------------------

TERMINAL_EMBER_JS_MANUAL_FOR_REFERENCE
