#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** BASH - OFTEN FORGOTTEN COMMANDS**'
echo '---------------------------------------------------------------------------------'
echo "rerun last command:                  !!"
echo "create soft link:                    ln -s file_to_link_to shortcut_name_location"
echo ""
echo '# POPD AND PUSHD'
echo "-  display popd + pushd stack:          dirs"
echo "-  clear popd + pushd stack:            dirs -c"
echo "-  display stack line-by-line           dirs -v"
echo ""
echo "# REVERSE CTRL-R SEARCH"
echo "-  cycle backward thru matches          <CTRL-SHIFT-R>"
echo "-  cycle forward thru matches           <CTRL-SHIFT-R>"
echo ""
echo "# EXECUTE STRINGS AS CODE OR TREAT CODE OUTPUT AS EMBEDDED TEXT"
echo "-  TODO: cover eval"
echo "-  TODO: cover \${}"
echo "-  TODO: cover \$()"
echo "-  TODO: cover \$SOMETHING"
echo "-  insert view history in backticks or eval:: example:         \`echo cat \$HOME/.bash_history\`"
echo ""
echo "# REMOVE AN ALIAS, FUNCTION, OR VARIABLE"
echo "-  remove an alias or method:                                  unalias aliasname"
echo "-  remove a variable:                                          unset variablename"
echo ""
echo "# SUPPRESS OR 'DISCONNECT' OUTPUT"
echo "-  suppress output:                                            some_command 2>/dev/null"
echo "-  run app detached from terminal:                             nohup some-app-eg-gimp &"
echo ""
echo "# GET META-INFO:: i.e. INFO ABOUT BASH COMMANDS, INCLUDING CUSTOM DEFINITIONS"
echo " -  Get command type:: fn, alias, app, built-in eg ls, etc:    type some-command" 
echo "    -- examples:                                               type ln"
echo "                                                               type gorails"
echo "                                                               type alias"
echo "     * can return function, alias, application location,  "
echo " - Output the actual code of a function or alias:              type function_name_here"
echo ''
echo ''# RENAME FILES
echo '' -  recursively change extension of all matching files:       rename -S .js .jsx --glob **/*.js
echo ''
echo '********** CURL ************'
echo ' - Save file received via curl by the name it is stored as on the server: example:'
echo '   curl --remote-name --location http://pilotfiber.dl.sourceforge.net/project/mcrypt/Libmcrypt/2.5.8/libmcrypt-2.5.8.tar.gz'
echo ''
echo "********* BATCH RENAME RECURSIVELY **********"
echo "find . -iname \"*.sublime-snippet\" -exec bash -c 'mv \"\$0\" \"\${0%\.sublime-snippet\}.cson\"' {} \;"
echo '---------------------------------------------------------------------------------\n'
