#!/usr/bin/env sh

cat <<-'TERMINAL_MANUAL_QUICK_REF'

----------------------------------------------------------------------------
** shebangs / hashbangs / #! **
----------------------------------------------------------------------------
-- Shebang at top of file tells OS what interpreter to execute file with

Bash shebang            #!/usr/bin/env bash
Shell shebang           #!/usr/bin/env sh
Ruby shebang            #!/usr/bin/env ruby
NodeJS shebang          #!/usr/bin/env node
ts-node shebang         #!/usr/bin/env ts-node     << i.e. Typescript Node
----------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
