#!/usr/bin/env sh

cat <<CURL_HEREDOC

-------------------------------------------------------------------------------------
** CURL **
-------------------------------------------------------------------------------------
curl to an output file - example:
    curl -o ./rake https://raw.githubusercontent.com/ai/rake-completion/master/rake
-------------------------------------------------------------------------------------

CURL_HEREDOC
