#!/usr/bin/env sh

cat << TERMINAL_MANUAL_QUICK_REF

---------------------------------------------------------------------------------
** BASH - CONDITIONALS (IF-THEN STATEMENTS, ETC.) **
---------------------------------------------------------------------------------
# CONTROL FLOW
- if-then one-liner:
      if [[ \"asdf\" = \"asdf\" ]]; then echo \"success!\"; fi

- if-then-else one-liner:
      if [[ \"asdf\" = \"asdf\" ]]; then echo \"success!\"; else; echo \"no match here\"; fi

- run if previous 2 commands succeed:
      if [[ cmd1 > /dev/null && cmd2 > /dev/null ]]; then echo success; else echo epic fail; fi

- run if previous command - with an arg - succeeds:
      if [[ \"touch ./cmd1\" > /dev/null ]]; then echo success; else echo epic fail; fi

# CONDITIONAL TESTS - BASICS
-  conditional equality test with variables:
      if [[ \"$T1\" = \"$T2\" ]]; then cmd; fi

-  conditional test operating on result of calling set of commands:
      value=\$( grep -ic \"benjamin\" /etc/passwd )
      if [[ \$value -eq 1 ]]

-  'greater than' numeric test conditional:
      if [[ \$value -gt 4 ]]; then ...; fi

-  'less than' numeric test conditional:
      if [[ \$value -lt 4 ]]; then ...; fi

-  check if a variable has something assigned to it:
      if [[ -n $woot ]]; then echo "win!"; else echo "nothing assigned"; fi

# FILE TESTS
-  check if file:
    -- exists:                       if [[ -e ~/.android/android.keystore ]]; then
                                       echo \"exists\"
                                     fi 

    -- isn't 0 size:                 if [[ -s ~/.android/android.keystore ]]; then
                                       echo "file isnt 0 size"
                                     fi

    -- isn't dir or device file:     if [[ -f ~/.android/android.keystore ]]; then
                                       echo "file isnt a dir or device file"
                                     fi

    -- is a directory:               if [[ -d ~/.android/android.keystore ]]; then
                                       echo "file is a dir"
                                     fi

    -- is a symbolic link:            if [[ -h ~/.android/android.keystore ]]; then
                                       echo "file is a symbolic link"
                                     fi

# PERMISSION TESTS
-  For given file, check if user running the test (same if tests as before, w/ diff flags):
    -- has read perm:                -r
    -- has write perm:               -w
    -- has write perm:               -x

# TODO:: MULTIPLE CONDITIONS IN ONE TEST
      if [[ "${RELEASE_MODE}" == "true" ]]; then echo "Release mode is true!"; fi

---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
