#!/usr/bin/env sh

cat <<-'TERMINAL_MANUAL_QUICK_REF'

---------------------------------------------------------------------------------
** Bash HEREDOCS **
---------------------------------------------------------------------------------
Display a HEREDOC to the terminal:

cat << MY_HEREDOC_NAME_HERE
Display this text!
Also display this!
MY_HEREDOC_NAME_HERE
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
