#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** Processing stdout text stream in CLI **'
echo '---------------------------------------------------------------------------------'
echo 'trim: remove trailing and leading whitespace. e.g. cat my-file.txt | trim'
echo ''
echo '## sort'
echo "   -- by text (alphabetical):   cat mytext.txt | sort"
echo "   -- by number:                cat mytext.txt | sort -n"
echo "   -- example:                example goes here"
echo ""
echo "## List item title:"
echo "   -- subitem here:           syntax here"
echo "   -- subitem here:           syntax here"
echo "   -- subitem here:           syntax here"
echo ""
echo '---------------------------------------------------------------------------------\n'
