#!/usr/bin/env sh

cat << END_OF_TERMINAL_MANUAL_FOR_BASIC_REFERENCE

---------------------------------------------------------------------------------
** USER INFO **
---------------------------------------------------------------------------------
- Get current user:      echo $USER

---------------------------------------------------------------------------------\n
END_OF_TERMINAL_MANUAL_FOR_BASIC_REFERENCE
