#!/usr/bin/env sh

cat <<-'END_OF_TERMINAL_MANUAL_FOR_BASIC_REFERENCE'

---------------------------------------------------------------------------------
** SYSTEM & FILE INFO **
---------------------------------------------------------------------------------
## Output system type                                     uname -a ack linux
## Get free disk space                                    df
## Get user login name                                    logname

# FILE INFO
## Show how command would be interpreted if used:         type
    *   e.g.:  type ls
    *   e.g.:  type man__system_info_get
    *   Provides info in numerous places "which" fails

---------------------------------------------------------------------------------

END_OF_TERMINAL_MANUAL_FOR_BASIC_REFERENCE
