#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** Processing stdout text stream in CLI **'
echo '---------------------------------------------------------------------------------'
echo 'trim: remove trailing and leading whitespace. e.g. cat my-file.txt | trim'
echo ''
echo '## sort'
echo "   -- by text (alphabetical):   cat mytext.txt | sort"
echo "   -- by number:                cat mytext.txt | sort -n"
echo ""
echo "## column: arrange output into neat columns:"
echo "   -- left-justified text in columns:  cat file.txt | column -t"
echo ""
echo "## gsub: replace one character or string in a stream with another"
echo '   -- replace one string with another:     awk "{gsub(/text-to-replace/,\"replacement-text\",\$0); print \$0}"'
echo '   -- replace on string stored in a var:   awk "{gsub(/$1/,\"replacement-text\",\$0); print \$0}'
echo '   -- remove substring from a string:      awk "{gsub(/text-to-replace/,\"\",\$0); print \$0}'
echo ''
echo "## get number of chars in each line piped in:  awk '{print length($0)}'"
echo ""
echo '---------------------------------------------------------------------------------\n'
