#!/usr/bin/env sh

cat << TERMINAL_MANUAL_QUICK_REF

---------------------------------------------------------------------------------
** ELIXIR **
---------------------------------------------------------------------------------
# Create Elixir project:                         mix new project-name --sup
  -- create a test suite (in new Elixir proj):  mix test

# IEX (Elixir REPL):                             iex
  -- in-iex help                                 h()
  -- compile a given Elixir file (from iex)      c(inputfile, outputfile)
  -- open iex within a project:                  iex -S mix

# RERUN ON CHANGE
  -- cli:         relixer [directory-or-file-to-watch] [elixir-file-to-run-on-change]
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
