#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** Ruby: often forgotten commands cheatsheet **'
echo '---------------------------------------------------------------------------------'
echo '- things I just cannot seem to remember in Ruby'
echo ""
echo "## Multiline strings          <<-STRINGNAME"
echo "                                text goes here"
echo "                              STRINGNAME"
echo "## pipe to ruby one-liner"
echo "        ffruby -pe:           cmd | ruby -pe '$_ = $_.modify_in_some_way' | cmd"
echo ""
echo "*** NUMBER TO NUMBERIC TYPE CONVERSIONS ***"
echo "5.kilobytes"
echo "5.megabytes"
echo "5.gigabytes"
echo "5.terabytes"
echo "5.petabytes"
echo ""
echo "5.seconds"
echo "5.minutes"
echo "5.hours"
echo "5.days"
echo "5.months"
echo ""
echo "*** PAUSE EXECUTION ***"
echo "sleep(numseconds)"
echo "   *   does not work properly in rake tasks!"
echo ""
echo "require 'something/somethingelse/file' calls are relative to the project root, not the current file"
echo '---------------------------------------------------------------------------------\n'

