#!/usr/bin/env sh

cat << TERMINAL_MANUAL_QUICK_REF

---------------------------------------------------------------------------------
** RSPEC **
---------------------------------------------------------------------------------
###### MATCHERS ######
 BE matchers
    be_truthy OR be:     expect("something").to be_truthy   # be === be_truthy
echo '    be_falsy:            expect("something").to be_falsy' 
    be_nil:              expect(obj).to be_nil
    not_to be:           expect(3).not_to be_nil
 INCLUDES
    include:             expect("a string").to include("a")
    not_to include:      expect("b string").not_to include("a")
    not_to include:      expect("b string").not_to include("a")
 EQUALS
    eq:                  expect("a string").to eq("a string")
    equal:               expect("a string").to equal("a string")   # => false
                          * passes if both --> same obj
 NUMERIC
    odd, even:           expect(3).to (be_odd)
    <, >:                expect(9).to (be < 10)
    be_an Integer:       expect(4).to (be_an(Integer))
    be_within:           expect(8).be_within(0.5).of(8.3)
 ERRORS
    raise_error:         expect { 3 / 0 }.to raise_error

---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
