#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** RUBY USAGE IN SHELL **'
echo '---------------------------------------------------------------------------------'
echo '- ruby cli gems'
echo ''
echo "## RERUN GEM:"
echo "   -- Custom watch pattern: use | to alternate. Example:"
echo '      rerun --pattern  "**/*.{rb,js,coffee,css,scss,erb,html,ru,yml,md,feature}|Rakefile" rake tasks'
echo ''
echo "## RAKE GEM:"
echo ' - args for rake tasks:'
echo "    * passing args to rake from terminal:"
echo "        *   one arg:                           rake sometask[arg]"
echo "        *   multiple args:                     rake sometask[arg1,arg2,arg3]"
echo "    * get rake task to access args (in Rakefile):"
echo "        task :sometask, [:arg1, arg2, ...] do |task, args|"
echo "            # all args  accessible through args.argname e.g. args.arg1"
echo "        end"
echo " - list rake tasks in a namespace e.g.:        rake -T db"
echo " - display rake task path e.g.:                rake -W db:migrate"
echo " - set environment to run rake task in e.g.:   RAILS_ENV=test rake db:migrate"
echo ' - view list of rake task prerequisites:       rake -P '
echo ' - view general rake tracing info:             rake --trace'
echo ' - view tracing info about rake rules:         rake --rules'
echo ""
echo " ## PIPE TO RUBY ONE-LINER:"
echo "        some_cmd | ruby -pe 'pipe to ruby one-liner, modify in some way' | cmd"
echo ""
echo " ## PARSE JSON RESPONSE FROM curl - EXAMPLE:" 
echo "        cat jsonfile.txt | ruby -pe 'require \"json\"; \$_ = JSON.parse(\$_)[0][\"cardnumber\"]'"
echo ""
echo ' ## RBENV'
echo ' - list all gems available to install:    rbenv install --list'
echo '---------------------------------------------------------------------------------\n'
