#!/usr/bin/env sh

cat <<-'TERMINAL_MANUAL_QUICK_REF'

---------------------------------------------------------------------------------
** sed cheatsheet **
---------------------------------------------------------------------------------
- find and replace text tool

## Insert a line into a file:          sed -i '2 i\\\text to insert' path/to/file
  -- insert 'text to insert' at line 2 of a file

## Find and replace from a stream:     ... | sed s/text-to-replace/new-text/g
  -- replace text-to-replace matches from a stream with new-text

## sed characters requiring escape:
  -- place a backslash before:         $.*/[\]^
  -- get single quote in output via:   '\''
  -- get single quote in output via:   '\''
  -- in replacement text, quote:       &\/

## find and replace from all files, recursively from current dir
  -- example:
      find . -name '*.sublime-snippet' -print0 | xargs -0 sed -i \"\" \"s/>source.js</>source.js, source.ts</g\"

## Replace in place (replace from stream):
    echo 'hi there' | sed 's/hi/hello/'
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
