#!/usr/bin/env sh

cat <<-'TERMINAL_MANUAL_QUICK_REF'

---------------------------------------------------------------------------------
** VIM **
---------------------------------------------------------------------------------
- random things I forget about vim
## Set syntax to ruby:                   :set syntax=ruby
## Turn numbers off:                     :set nonumber
## Turn numbers on:                      :set number

***** INLINE CONSOLE *****
## Open a console in current panel       :e term://bash
## Open a console in new panel below:    :sp term://bash
## Open a console in new panel to right: :vsp term://bash

**** FIND AND REPLACE EXAMPLES *****
remove start-of-line irb(main):020:0> + a space    < :%s/irb(main):.*>\s//g
remove start-of-line => + a space                  :%s/^=>\s//g

**** REMAP KEYS ****
:map   OR map!
   * show list of existing key maps:
       map     OR    map!
   * map a sequence of keys to another sequence of keys: generic:
       :map #{key} :#{output 
   * example: maps F2 to show current date and time:
        map <F2> :echo 'Current time is ' . strftime('%c')<CR>
   * example: maps <F3> to insert current current date and time in current buffer:
        map! <F3> <C-R>=strftime('%c')<CR>
:noremap
   * define literal keymap: no key substitutions
:unmap
   * unmap a key you no longer want mapped:       unmap <F8>    OR unmap! <F8>
## REMAP MODES: i.e. prefix before map, unmap, nnoremap:
  i       e.g. :imap - insert mode maps
  v       e.g. :vmap - visual and select mode maps
  s       e.g. :smap - select mode maps
  x       e.g. :xmap - visual mode maps
  c       e.g. :cmap - command-line mode maps
  o       e.g. :omap - operator pending mode maps

mapleader: 

**** AUTORUN A COMMAND BEFORE VIM STARTS (E.G. KEY MAPPING) ****
autocmd VimEnter
   * do something immediately when vim starts. Example:
        autocmd * unmap! <F8>
autocmd FileType #{some file type} #{cmd}
   * do something immediately when vim loads a specific file type. Example:
        autocmd Filetype python unmap! <F8>
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
