#!/usr/bin/env sh

cat <<-'TERMINAL_MANUAL_QUICK_REF'

---------------------------------------------------------------------------------
** URI DECODING **
---------------------------------------------------------------------------------
# Ruby uri decoding
-- may need import lib first:        require "uri"
-- unescape: rm crazy browser text:  URI.unescape("http://example.com/?a=%09%0D")
-- escape:  add crazy browser text:  URI.escape("http://example.com/?a=\\t\\r")
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
