#!/usr/bin/env sh

echo ''
echo '---------------------------------------------------------------------------------'
echo '** at bash tool**'
echo '---------------------------------------------------------------------------------'
echo '- schedule tasks'
echo ''
echo "## List all scheduled task:        atq" 
echo "## Delete a task:                  atrm 1      << if the task # is 1" 
echo "   -- (definition of first item goes here)"
echo "   -- example:                example goes here"
echo ""
echo "## List item title:"
echo "   -- subitem here:           syntax here"
echo "   -- subitem here:           syntax here"
echo "   -- subitem here:           syntax here"
echo ""
echo '---------------------------------------------------------------------------------\n'
