#!/usr/bin/env sh

cat << TERMINAL_MANUAL_QUICK_REF

---------------------------------------------------------------------------------
** Ruby: often forgotten commands cheatsheet **
---------------------------------------------------------------------------------
- things I just cannot seem to remember in Ruby

## Multiline strings  <<-STRINGNAME
                        text goes here
                      STRINGNAME
## pipe to ruby one-liner
    ffruby -pe:           cmd | ruby -pe '$_ = $_.modify_in_some_way' | cmd

*** NUMBER TO NUMBERIC TYPE CONVERSIONS ***
5.kilobytes
5.megabytes
5.gigabytes
5.terabytes
5.petabytes

5.seconds
5.minutes
5.hours
5.days
5.months

*** PAUSE EXECUTION ***
sleep(numseconds)
   *   does not work properly in rake tasks!

require 'something/somethingelse/file' calls are relative to the project root, not the current file
---------------------------------------------------------------------------------

TERMINAL_MANUAL_QUICK_REF
