// Sample .eslintrc file if you're using babel:

{
	"rules": {
		"no-new-wrappers": 2,
		"no-new-func": 2,
		"no-new-object": 2,
		"no-array-constructor": 2,

		"no-console": 0,
		"no-eval": 2,
		"no-implied-eval": 2,
		"no-fallthrough": 2,
		"no-undef-init": 2,
		"no-with": 2,
		"no-undefined": 2,
		"no-void": 2,

		"key-spacing": [2, {"beforeColon": false, "afterColon": true, "align": "value"}],
		"no-spaced-func": 2,
		"space-infix-ops": 2,
		"semi-spacing": [2, {"before": false, "after": true}],
		"space-before-function-paren": [2, "always"],
		"space-before-blocks": 1,
		"space-in-parens": [2, "never"],
		"space-return-throw-case": 2,
		"template-curly-spacing": 1,
		"comma-spacing": [2, {"before": false, "after": true}],
		"arrow-spacing": 1,

		"indent": [2, "tab"],
		"quotes": [1, "single"],
		"linebreak-style": [2, "unix"],
		"semi": [2, "always"],
		"eqeqeq": 2,
		"comma-style": [2, "last"],

		"no-self-compare": 2,
		"no-warning-comments": [1, { 
			"terms": ["todo", "hack", "fixme", "evil"],
			"location": "start" 
		}],
		"wrap-iife": [2, "outside"],
		"no-shadow": 2,
		"new-cap": [2, {"capIsNew": false, "newIsCap": true}],
		"consistent-this": [2, "self"],
		"no-lonely-if": 2,
		"no-useless-call": 2,
		"no-unexpected-multiline": 2,
		"no-extra-semi": 2,
		"no-useless-concat": 2,
		"no-sequences": 2,
		"no-else-return": 1,
		"no-shadow-restricted-names": 2,
		"no-use-before-define": [2, "nofunc"],
		"default-case": 2,
		"no-path-concat": 2,
		"quote-props": [1, "as-needed"],
		"no-negated-condition": 2,
		"max-len": [1, 100, 2, {"ignoreUrls": true}],

		"no-var": 1,
		"prefer-const": 1,
		"no-const-assign": 2,
		"object-shorthand": 1,
		"array-callback-return": 1,
		"prefer-template": 1,
		"func-style": [1, "declaration", { "allowArrowFunctions": true }],
		"no-loop-func": 2,
		"no-param-reassign": 1,
		"prefer-spread": 1,
		"prefer-arrow-callback": 1,
		"arrow-parens": [1, "as-needed"],
		"arrow-body-style": 1,
		"no-confusing-arrow": 1,
		"no-useless-constructor": 2,
		"no-dupe-class-members": 2
	},
  "parser": "babel-eslint",
	"env": {
		"es6": true,
		"node": true,
		"browser": true
	},
	"extends": "eslint:recommended",
	"ecmaFeatures": {
		"jsx": true,
		"experimentalObjectRestSpread": true,
		"generators": true,
		"arrowFunctions": true,
		"defaultParams": true,
		"spread": true,
		"restParams": true,
		"blockBindings": true,
		"templateStrings": true,
		"destructuring": true,
		"forOf": true,
		"regexUFlag": true,
		"regexYFlag": true,
		"objectLiteralComputedProperties": true,
		"objectLiteralShorthandProperties": true,
		"objectLiteralShorthandMethods": true,
		"objectLiteralDuplicateProperties": true,
		"classes": true
	},
	"plugins": [
		"react"
	]
}