#!/usr/bin/env bash

create-react-app $1
cd $1
npm run eject

# add redux
npm install --save redux react-redux

# add sass
npm install --save-dev sass-loader css-loader style-loader

cat <<-HEREDOC
-------------------------------------------------------------------------
Add the following to your webpack config file, in the loaders section
{
   test: /\.scss$/,
   loaders: ['style', 'css', 'sass']
}
-------------------------------------------------------------------------
HEREDOC

