; call JS' console.log with more convenient syntax, without logging the location of
; the call as being in a "log" function (the code is inline since it's generated by
; a macro, and thus acts as if you typed out the full call to console.log each time)
(defmacro log [msg]
  `(.log js/console ~msg))

; return the time the code was compiled / built (rather than the time it was run).
; works because macros are run at compile-time not run-time
(defmacro build-time []
  (str (java.util.Date.)))

