#!/usr/bin/env ruby

require 'optparse'
require 'colorize'

def show_help
	puts "\nUsage:  catr [find=]regexp|string [OPTIONS] [OPTIONAL_PARAMS]"
	puts "\nESSENTIAL ARGUMENTS"
	puts "   find=[string|regex]   string or regular expression to search for in all files."
	puts "                         Returns matching files, along with the line you can find each"
	puts "                         match at. "
	puts "   - Can also just be defined as a bare 1st argument, no find="
	puts "\nOPTIONS:"
	puts "   --function                only match lines with functions"
	puts "   --console                 only match lines with calls to console"
	puts "   --nocomment               exclude // comment lines"
	puts "   --match_only              show just the matching part, rather than the entire matching"
	puts "                             line (with the matching part highlighed"
	puts "\nOPTIONAL_PARAMS:"
	puts "   ftype=[string|regex]      filetype (technically it matches any part of a filepath)"
	puts "   exclude=[string|regex]    exclude files with this matching group in the path"
	puts "   exclude_find=[str|regex]  exclude files with this matching group in the content (text)"
	puts "   match_path=[str|regex]    only include files with this match in their path"
	puts "\nSAVED_SEARCHES: (these override all other params given"
	puts "   --seneca                  search .js files for 'seneca'"
	puts "   --seneca.add              search .js files for places seneca actions are declared"
	puts "   (not truly any saved searches yet - just predefined)"
	puts "\nEXAMPLES:"
	puts 'catr [^\w\d\.]seneca[^\(]*[\(][^\{]*\) type=.js exclude=node_modules --nocomment --match_only'
	puts "   - match files of type .js containing 'seneca' that don't have node_modules in their"
	puts "     path. Show only the match, not the full line. Exclude lines that are commented out."
	puts "\n"
	puts 'catr global type=.js exclude=node_modules --nocomment --match_only'
	puts "   - match files of type .js containing 'global' that don't have node_modules in their"
	puts "     path. Show only the match, not the full line. Exclude lines that are commented out."
	puts "\n"
	puts "catr global ftype=js exclude=min --nocomment exclude_find=this"
	puts "   - match on the word global in js files, exclude min files & lines with the word 'this'"
	puts "\n"
	puts 'catr [^\w\d]seneca[^\W\D] type="js" exclude="node_modules" --nocomment'
	puts "   - match on full word seneca in js files, w/ path node_modules & comment lines excluded"
	puts "\n"
	puts "catr seneca ftype='js$' exclude=min"
	puts "   - ftype regex example. matches 'seneca' in js but NOT jsx, json, or min.js files"
	puts "\n"
	puts 'catr [uU]ser type="js" exclude="node_modules" --function'
	puts "   - match functions in js files w/ word user in them, exclude paths w/ node_modules"
	puts ""
	exit!
end

# show help if user put too few arguments in...then stop the program
if ARGV.length == 0
	show_help
end

# get all files downward in file system tree from current working directory
def get_files
	Dir.glob("**/*").select{ |file|
		File.file?(file)
	}
end

# gets content of all files, places them in a hash. files is an array of filenames
def fname_cat_hash(files)
	files.reduce({}) { |filehash, file_name|
		File.open(file_name) do |myfile|
			lines_array = myfile.reduce([]) { |file_lines, line|
				file_lines.push(line)
				file_lines
			}
			filehash[file_name] = lines_array
			filehash
		end
	}
end

# display formatted form of the file name
def show_fname(fname)
	len = fname.length
	puts "\n#{fname}"
	len.times{||print "*"}
	puts ""
	fname
end

def apply_special_filters(text, args)
	if args[:function]
		text.pop if ! text.last.match(/(?!<[^a-zA-Z0-9_])function(?=[^a-zA-Z0-9_])/)
	end
	if args[:console]
		text.pop if ! text.last.match(/(?!<[^a-zA-Z0-9_])console(?=[^a-zA-Z0-9_])/)
	end
	text
end

module SavedSearches
	SAVED_SEARCHES_HASH = {
		"seneca"=>Proc.new { |args|
				args[:find] = "seneca"
				args[:ftype] = "js$"
				args[:exclude_find] = "/xafoijrgnviaewugfheaogiavfg/"
				args
		},
		#aims to identify all locations in which seneca actions are defined
		"seneca.add"=>Proc.new { |args|
			lookbehind = "(?<![^a-zA-Z0-9_][_R])"

			sen_add_call="([\s]|this|seneca|root|instance|router)\\.add"
			sen_spacer="\s?\\(\s?\s?['\"\{]"
			sen_args = "(.*(role|cmd|init|deprecate\$|hook|type|list|stats|get|info|ready|pinthis):)*"
			endpt = "([^\}]*)[^\}]*\}"

			O_R_1 = "(seneca\\.add)|(role:[\s\"']?[\s\"']?seneca)|(private\$\.actrouter\.add\s?\\()"
			O_R_2 = "(\.add.*seneca)|pinthis\.add\s?\\(.*(pattern|meta)|(this\.add\s?\\(.*#{sen_args})"
			O_R_3 = "((?<=\\(\{\n).*$)"
			overrides = "(#{O_R_1}|#{O_R_2}|#{O_R_3})"

			args[:find] = "((#{lookbehind}#{sen_add_call}#{sen_spacer}#{sen_args}#{endpt})|#{overrides})"
			args[:ftype] = "js$"
			args[:exclude_find] = "/xafoijrgnviaewugfheaogiavfg/"
			args[:exclude] = "min"
			args[:match_only]=false
			args
		}
	}
end

# # place searches you want to be able to do any time in here
# def load_saved_srch(args, saved_search)
# 	SavedSearches::SAVED_SEARCHES_HASH.each {|key, saved_search_proc|
# 		if saved_search == key
# 			puts 'IN!'
# 			args = saved_search_proc.call(args)
# 		end
# 	}
# 	args
# end

# emulates scrub for earlier versions of ruby
def scrub(str)
	str.encode('UTF-16', :invalid => :replace, :replace => '').encode('UTF-8')
end

# return matching content, including the line number
def search_content(fname, content, args)
	lnum = 0
	output = content.reduce([]) { |text, line|
		lnum = lnum.next
		begin
			if args[:find].match(scrub(line)) && (! args[:exclude_find].match(scrub(line)))
				if ! args[:nocomment] ||
						(args[:nocomment] && args[:find].match(scrub(line)).to_s.split('/').length < 2)
					text.push("#{lnum}: #{args[:find].match(scrub(line)).to_s.strip}")
					text = apply_special_filters(text, args)
				end
			end
		rescue
			puts "\n\n\n\n\n\n\n"
			puts "FAIL!"
			puts scrub(line)
			puts "\n\n\n\n\n\n\n"
		end
		text
	}
	show_fname(fname) if not output.empty?
	output
end

# output the file data that matches the find (calls the find)
def prep_find_args(fname, content, args, printer)
	# convert various args to regexes if they aren't already
	args[:orig_find] 		= args[:orig_find] || args[:find]
	args[:find] 				= to_match_only_regex(args[:find], args[:match_only])
	args[:exclude] 			= to_regexp(args[:exclude]) 			if args[:exclude]
	args[:exclude_find] = to_regexp(args[:exclude_find]) 	if args[:exclude_find]
	args[:ftype] 				= to_regexp(args[:ftype]) 				if args[:ftype]
	args[:match_path] 	= to_regexp(args[:match_path]) 		if args[:match_path]
	printer.call(search_content(fname, content, args), args[:orig_find])
end

# turn a regex arg into a rewgex that matches entire line the original regex would've matched
def to_match_only_regex(str, match_only)
	if str.class == String && (! match_only)
		clean_str = str.gsub(/^\^/, "").gsub(/\$$/, "")
		puts clean_str
		str = ".*#{clean_str}.*"
	end
	to_regexp(str)
end

# convert string to regular expression
def to_regexp(str)
	if str.class == String
		Regexp.new(str.gsub(/\/\w?$/, "").gsub("/", ""))
	else
		str
	end
end

# used to actually match arguments of interest
def match_args(arg, opts, keys)
	keys.reduce(opts) {|options, key|
		if arg.match("=") && (arg.include? key.to_s)
			arg_arr = arg.split("=")
			if arg_arr[0] == key.to_s
				options[arg_arr[0].to_sym] = arg_arr[1]
			end
		end
		options
	}
end

#request the arguments of interest
def get_args(argv, arg_list)
	argv.reduce({}) do |opts, arg|
		opts = match_args(arg, opts, arg_list)
		opts
	end
end

# get a single flag argument
def flag_arg(argv, args, addition)
	args[addition.to_sym] = ((argv.include? addition) || (argv.include? "--#{addition}"))
	args
end

# get ALL single flag arguments (from an array passed in)
def flag_args(argv, args, new_args)
	new_args.reduce(args) { |margs, magic_arg|
		flag_arg(argv, margs, magic_arg)
	}
end

# initialize the saved searches, which can be run at a whim with predefined params
def load_saved_searches(args, argv)
	if SavedSearches::SAVED_SEARCHES_HASH.any? { |saved_search_name, saved_search_proc|
		if argv.include? "--#{saved_search_name}"
			puts saved_search_name
			args = saved_search_proc.call(args)
		end
	}
	end
	args
end

# initialize params passed in from terminal
def arg_setup(param_args, flag_args)
	args = get_args(ARGV, param_args)
	args = flag_args(ARGV, args, flag_args)
	if ! args[:find] && param_args.concat(flag_args).include?(ARGV[0])
		show_help
	elsif ! args[:find] && ! param_args.concat(flag_args).include?(ARGV[0])
		args[:find] = ARGV[0]
	end
	args[:exclude_find] = /xafoijrgnviaewugfheaogiavfg/ if ! args[:exclude_find]
	args = load_saved_searches(args, ARGV)
	args
end

# special printing function, to allow colorized printing of nb section
printer = Proc.new {|data, orig_find|
	orig_matches = data.to_s.match(orig_find)
	if orig_matches
		data.each {|line|
			orig_match = line.match(orig_find)
				output = line.split(to_regexp(orig_match).to_s)
				print output[0]
				print orig_match.to_s.green
				print "#{output[1]}\n"
		}
	end
}

## TOOL ACTUALLY RUNS HERE ##

# grab the args
args = arg_setup(["find", "ftype", "exclude", "exclude_find", "match_path"],
								 ["function", "match_only", "nocomment", "console"])

# actually display the filenames and matching content below
fname_cat_hash(get_files).each { |fname, content|
	p_match = !args[:match_path] || fname.match(args[:match_path])
	# if filetype was given, only let matching files through; otherwise let all files through
	if (p_match && (args[:ftype] && fname.split(".").last.match(args[:ftype])) || (! args[:ftype]))
		# Exclude filenames with the exclude
		if (! args[:exclude]) || (args[:exclude] && ! fname.match(args[:exclude]))
			prep_find_args(fname, content, args, printer)
		end
	end
}
