#!/usr/bin/env ruby

require 'fileutils'

def prepend_line_to_file(file, line_number_to_delete)
  original_file = "./#{file}"
  new_file = "#{original_file}.new"
  counter = 1
  File.open("#{new_file}", 'w') do |fo|
    File.foreach(original_file) do |li|
      if counter != line_number_to_delete.to_i
        puts li
        fo.puts li
      end
      counter = counter + 1
    end
  end
  File.delete("#{original_file}")
  File.rename("#{new_file}", "#{original_file}")
end

def usage(error)
  puts error
  puts "-- delete_line -------------------------------------------"
  puts "USAGE:       prepend_text filename \"line to delete\""
  puts "-----------------------------------------------------------"
end

if __FILE__ == $0
  if ARGV.count != 2
    usage "Wrong number of arguments given to delete_line utility."
  elsif !File.exists?("./#{ARGV[0]}") && !ARGV.include?("-f")
    usage "file does not exist"
  else
    prepend_line_to_file(ARGV[0], ARGV[1])
    puts "END!"
  end
end
